name: sheikh_muhammed_zeyn
description: "A new Flutter project with feature-based architecture."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # UI packages
  flutter_svg: ^2.0.9 # For SVG icons
  lottie: ^3.0.0 # For Lottie animations
  cached_network_image: ^3.3.1 # For caching network images

  # State management
  provider: ^6.1.1

  # Navigation
  go_router: ^13.0.1

  # Utils
  intl: ^0.19.0 # For internationalization
  shared_preferences: ^2.2.2 # For local storage
  logger: ^2.0.2+1 # For logging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/drawable-hdpi/
    - assets/images/drawable-ldpi/
    - assets/images/drawable-mdpi/
    - assets/images/drawable-xhdpi/
    - assets/images/drawable-xxhdpi/
    - assets/images/drawable-xxxhdpi/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
